name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: Breaking Changes 🛠
    labels:
      - breaking
  - title: 🏕 Features
    labels:
      - feature
  - title: Fixes 🔧
    labels:
      - fix
  - title: Other Changes
    labels:
      - "*"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: "chore"
    title:
      - "/chore/i"
  - label: "docs"
    title:
      - "/chore/i"
  - label: "bug"
    title:
      - "/fix/i"
  - label: "enhancement"
    title:
      - "/fix/i"
  - label: "breaking"
    title:
      - "/.*!:/i"
exclude-labels:
  - "ignore-for-release"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "fix"
      - "chore"
  default: patch
template: |
  ## Changes

  $CHANGES
